Vagrant.configure("2") do |config|
  config.vm.define "nexus" do |nexus|
    nexus.vm.box_download_insecure = true
    nexus.vm.box = "hashicorp/bionic64"
    nexus.vm.network "private_network", ip: "100.0.0.16"
    nexus.vm.synced_folder "./data", "/opt/sonatype-work/nexus3", disabled: false
	nexus.vm.network "forwarded_port", guest: 22, host: 2448
	nexus.vm.provision "shell", path: "test.sh"
    nexus.vm.hostname = "nexus"
    nexus.vm.provider "virtualbox" do |v|
      v.name = "nexus"
      v.memory = 2048
      v.cpus = 1
    end
  end
end